package JDBC;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

public class Problem15_AutoGeneratedKeys {

    public static void main(String[] args) {

        String sql =
                "INSERT INTO Employee "
                + "(name, department_id, salary) "
                + "VALUES (?, ?, ?)";

        try (Connection connection =
                     DBConnection.getConnection();

             PreparedStatement statement =
                     connection.prepareStatement(
                             sql,
                             Statement.RETURN_GENERATED_KEYS
                     )) {

            statement.setString(1, "Riya");
            statement.setInt(2, 101);
            statement.setDouble(3, 55000);

            int rows =
                    statement.executeUpdate();

            if (rows == 1) {

                try (ResultSet keys =
                             statement.getGeneratedKeys()) {

                    if (keys.next()) {

                        int generatedId =
                                keys.getInt(1);

                        System.out.println(
                                "Employee inserted."
                        );

                        System.out.println(
                                "Generated ID: "
                                + generatedId
                        );
                    }
                }
            }

        } catch (Exception e) {

            e.printStackTrace();
        }
    }
}